from __future__ import annotations

import json
import os
import time
from dataclasses import dataclass
from sys import platform
from time import sleep
from typing import Dict, TypedDict

from EDlogger import logger


@dataclass
class FleetCarrierRawCargo:
    """ The cargo data as stored in the Fleet Carrier data json file. """
    commodity: str  # i.e. "Ceramiccomposites"
    locName: str  # i.e. "Ceramic Composites"
    mission: bool  # True if a mission commodity
    originSystem: int | None  # The system number. i.e. 9466510910865
    qty: int  # i.e. 500
    stolen: bool  # True if stolen
    value: int  # i.e. 5448


class FleetCarrierCargo(TypedDict):
    """ Simplified cargo data. """
    commodity: str  # i.e. "Ceramiccomposites"
    locName: str  # i.e. "Ceramic Composites"
    qty: int  # i.e. 5448


class FleetCarrierMonitorDataParser:
    """ Parses the FleetCarrier.json file generated by the game. """

    def __init__(self, file_path=None):
        self.file_path = file_path
        self.last_mod_time = None

        # Read json file data
        self.current_data = self.get_fleetcarrier_data()

        # self.watch_thread = threading.Thread(target=self._watch_file_thread, daemon=True)
        # self.watch_thread.start()
        # self.status_queue = queue.Queue()

    # def _watch_file_thread(self):
    #     backoff = 1
    #     while True:
    #         try:
    #             self._watch_file()
    #         except Exception as e:
    #             logger.debug('An error occurred when reading status file')
    #             sleep(backoff)
    #             logger.debug('Attempting to restart status file reader after failure')
    #             backoff *= 2
    #
    # def _watch_file(self):
    #     """Detects changes in the Status.json file."""
    #     while True:
    #         status = self.get_cleaned_data()
    #         if status != self.current_data:
    #             self.status_queue.put(status)
    #             self.current_data = status
    #         sleep(1)

    def get_file_modified_time(self) -> float:
        return os.path.getmtime(self.file_path)

    def get_fleetcarrier_data(self):
        """Loads data from the JSON file and returns the data, or None if the file does not exist.
        The data format is detailed here:
        https://github.com/EDCD/FDevIDs/blob/master/Frontier%20API/FrontierDevelopments-CAPI-endpoints.md#fleetcarrier
        Here is a sample section:
        {
          "data": {
            "balance": "490820542",
            "blackmarketFinances": {
              "allTimeProfit": 0,
              "balanceAllocForPurchaseOrders": 0,
              "cargoTotalValue": 0,
              "numCommodsForSale": 0,
              "numCommodsPurchaseOrders": 0
            },
        """
        if not self.file_path:
            return None

        # Check file if exists
        if not os.path.exists(self.file_path):
            return None

        # Check if file changed
        if self.get_file_modified_time() == self.last_mod_time:
            #logger.debug(f'FleetCarrier.json mod timestamp {self.last_mod_time} unchanged.')
            return self.current_data

        # Read file
        backoff = 1
        while True:
            try:
                with open(self.file_path, 'r', encoding='utf-8') as file:
                    data = json.load(file)
                    break
            except Exception as e:
                logger.debug('An error occurred reading FleetCarrier.json file. File may be open.')
                sleep(backoff)
                logger.debug('Attempting to re-read FleetCarrier.json file after delay.')
                backoff *= 2

        # Store data
        self.current_data = data
        self.last_mod_time = self.get_file_modified_time()
        #logger.debug(f'FleetCarrier.json mod timestamp {self.last_mod_time} updated.')
        # print(json.dumps(data, indent=4))
        return data

    def get_current_cargo_list(self) -> list[FleetCarrierRawCargo] | None:
        """ Gets the Fleet Carrier cargo as a list. This may include duplicate items for the same commodity because of
        the mission, original system, stolen and value fields.
        Will not trigger a read of the json file.
        @return A list of FleetCarrierRawCargo items
        """
        if not self.current_data:
            return None

        _cur_data = self.current_data['data']
        raw_cargo_list = _cur_data['cargo']
        cargo_list = [FleetCarrierRawCargo(commodity=item["commodity"],
                                           locName=item["locName"],
                                           mission=item["mission"],
                                           originSystem=item["originSystem"],
                                           qty=item["qty"],
                                           stolen=item["stolen"],
                                           value=item["value"]
                                           ) for item in raw_cargo_list]

        return cargo_list

    def get_consolidated_cargo_dict(self) -> dict[str, FleetCarrierCargo] | None:
        """ Gets a consolidated alphabetically sorted dict of cargo items from the current data.
        Will not trigger a read of the json file. """
        # Get the raw cargo list with possible duplicates.
        raw_cargo = self.get_current_cargo_list()
        if not raw_cargo:
            return None

        # Sort alphabetically
        sorted_raw_cargo = sorted(raw_cargo, key=lambda x: x.locName.lower())

        cons_cargo: dict[str, FleetCarrierCargo] = {}
        for item in sorted_raw_cargo:
            loc_name = item.locName
            if loc_name in cons_cargo:
                # Update qty
                cons_cargo[loc_name]['qty'] = cons_cargo[loc_name]['qty'] + item.qty
            else:
                # Add item
                cons_cargo[loc_name] = FleetCarrierCargo(commodity=item.commodity,
                                                         locName=item.locName,
                                                         qty=item.qty)

        return cons_cargo


# Usage Example
if __name__ == "__main__":
    parser = FleetCarrierMonitorDataParser()
    parser.file_path = r"C:\Users\shuttle\AppData\Local\EDMarketConnector\plugins\fleetcarriermonitor\FleetCarrier.V2V-65W.json"
    parser.get_fleetcarrier_data()
    if parser.current_data:
        cur_data = parser.current_data['data']
        print(cur_data['name']['callsign'])

        y1 = parser.get_consolidated_cargo_dict()
        for comm in y1:
            print(comm)
    # while True:
    #     print(parser.current_data)
    #     time.sleep(1)
